language: python
sudo: false
python:
    - "3.5"
    - "3.6"
install:
    - pip install -r requirements.txt
    - python setup.py -q install
script:
    - cd 
    - pwd
    - python -c "import plotenv; plotenv.initialize(); print('Success!')"
